/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/cesium/': RouteRecordInfo<'/cesium/', '/cesium', Record<never, never>, Record<never, never>>,
    '/cesium/volume-rendering/cloud': RouteRecordInfo<'/cesium/volume-rendering/cloud', '/cesium/volume-rendering/cloud', Record<never, never>, Record<never, never>>,
    '/cesium/volume-rendering/perlin': RouteRecordInfo<'/cesium/volume-rendering/perlin', '/cesium/volume-rendering/perlin', Record<never, never>, Record<never, never>>,
    '/threejs/': RouteRecordInfo<'/threejs/', '/threejs', Record<never, never>, Record<never, never>>,
  }
}
